services:
  oa-mysql:
    container_name: openaccounting-mysql
    image: mariadb:11.1.2
    networks:
      - network1
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: openaccounting
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "exit | mariadb -h localhost -P 3306 -u root -psecret"]
      interval: 15s
      timeout: 10s
      retries: 3 

# You can connect to the mysql database with:
# docker exec -it openaccounting-mysql mariadb -u root -psecret -h localhost --protocol tcp openaccounting

  oa-server:
    container_name: openaccounting-server
    build: server/
    networks:
      - network1
    ports:
      - 8080:8080
    depends_on:
      oa-mysql:
        condition: service_healthy

  oa-web:
    container_name: openaccounting-web
    build: web/
    ports:
      - 4200:4200

networks:
  network1:
    internal: false

