services:
  oa-mysql:
    container_name: openaccounting-mysql
    image: mariadb:11.1.2
    networks:
      - network1
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: openaccounting
    healthcheck:
      test: ["CMD-SHELL", "exit | mariadb -h localhost -P 3306 -u root -psecret"]
      interval: 15s
      timeout: 10s
      retries: 3 

  oa-server:
    container_name: openaccounting-server
    build: server/
    networks:
      - network1
    depends_on:
      oa-mysql:
        condition: service_healthy

  oa-web:
    container_name: openaccounting-web
    build: web/
    networks:
      - network1

  oa-proxy:
    container_name: openaccounting-proxy
    build: proxy/
    networks:
      - network1
      - network2
    ports:
      - 8080:8080
      - 4200:4200

networks:
  network1:
    internal: true
  network2:
    internal: false
